version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/timely
      FROM_EMAIL: secret # Use Gmail Account Credentials - Email Address - I have this set up in Heroku to timely.email.sender@gmail.com
      FROM_PW: secret # Use Gmail Account Credentials - Email Password
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: ./dockerfiles/postgres.dockerfile
    ports:
      - 5432:5432
    user: postgres
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
